"""Behaviour Exploration — general behaviour and maze-specific measures across sessions.

Provides behavioural summaries (speed, movement, HD occupancy, light/dark comparisons)
using pooled sync.h5 data from all sessions.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "src"))

from frontend.data import load_all_sync_data, session_filter_sidebar
from hm2p.plotting import format_pvalue, paired_condition_scatter

log = logging.getLogger("hm2p.frontend.behaviour")

st.title("Behaviour Exploration")
st.caption(
    "General behaviour analysis and maze-specific measures across all sessions. "
    "Speed, movement, head direction occupancy, and light/dark behavioural comparisons."
)

# ── Load pooled data ────────────────────────────────────────────────────
with st.spinner("Loading sync data for all sessions..."):
    all_data = load_all_sync_data()

if all_data["n_sessions"] == 0:
    st.warning(
        "No data available yet. This page will populate when sync.h5 files "
        "are generated by the pipeline."
    )
    st.stop()

# ── Sidebar filters (no ROI filter needed — this page is behaviour only) ──
sessions = session_filter_sidebar(
    all_data["sessions"], show_roi_filter=False, key_prefix="behav"
)

if not sessions:
    st.warning("No sessions match the current filters.")
    st.stop()

st.markdown(f"**{len(sessions)} sessions** loaded")

# ── Colour mapping ──────────────────────────────────────────────────────
CELLTYPE_COLORS = {"penk": "#1f77b4", "nonpenk": "#ff7f0e", "unknown": "#999999"}


# ── Helper: compute per-session behavioural summary ──────────────────────
def _session_summary(s: dict) -> dict:
    """Compute behavioural summary stats for a single session."""
    ft = s["frame_times"]
    speed = s["speed_cm_s"]
    hd = s["hd_deg"]
    light_on = s["light_on"]
    active = s["active"]
    bad = s["bad_behav"]
    good = ~bad

    # Time
    dt = np.median(np.diff(ft)) if len(ft) > 1 else 1.0
    total_dur = ft[-1] - ft[0] if len(ft) > 1 else 0.0
    active_frac = float(np.mean(active[good])) if good.any() else 0.0

    # Speed (good frames only)
    good_speed = speed[good]
    mean_speed = float(np.nanmean(good_speed)) if len(good_speed) > 0 else 0.0
    median_speed = float(np.nanmedian(good_speed)) if len(good_speed) > 0 else 0.0

    # Distance
    distance_cm = float(np.nansum(speed[good] * dt))

    # Light/dark time
    light_time = float(np.sum(light_on[good]) * dt)
    dark_time = float(np.sum(~light_on[good]) * dt)

    # Angular head velocity
    hd_rad = np.deg2rad(hd)
    dhd = np.diff(hd_rad)
    # Unwrap angular differences to [-pi, pi]
    dhd = np.arctan2(np.sin(dhd), np.cos(dhd))
    ahv = np.abs(dhd) / dt  # rad/s -> convert to deg/s
    ahv_deg = np.rad2deg(ahv)
    # Only good frames (ahv has length n-1, so use good[1:] & good[:-1])
    good_ahv_mask = good[1:] & good[:-1]
    mean_ahv = float(np.nanmean(ahv_deg[good_ahv_mask])) if good_ahv_mask.any() else 0.0

    # Light vs dark speed
    light_mask = light_on & good
    dark_mask = ~light_on & good
    speed_light = float(np.nanmean(speed[light_mask])) if light_mask.any() else np.nan
    speed_dark = float(np.nanmean(speed[dark_mask])) if dark_mask.any() else np.nan

    # Light vs dark active fraction
    active_light = float(np.mean(active[light_mask])) if light_mask.any() else np.nan
    active_dark = float(np.mean(active[dark_mask])) if dark_mask.any() else np.nan

    # Light vs dark AHV
    light_ahv_mask = light_on[1:] & light_on[:-1] & good_ahv_mask
    dark_ahv_mask = ~light_on[1:] & ~light_on[:-1] & good_ahv_mask
    ahv_light = float(np.nanmean(ahv_deg[light_ahv_mask])) if light_ahv_mask.any() else np.nan
    ahv_dark = float(np.nanmean(ahv_deg[dark_ahv_mask])) if dark_ahv_mask.any() else np.nan

    return {
        "exp_id": s["exp_id"],
        "animal_id": s["animal_id"],
        "celltype": s["celltype"],
        "total_dur_s": total_dur,
        "active_frac": active_frac,
        "mean_speed": mean_speed,
        "median_speed": median_speed,
        "distance_cm": distance_cm,
        "light_time_s": light_time,
        "dark_time_s": dark_time,
        "mean_ahv_deg_s": mean_ahv,
        "speed_light": speed_light,
        "speed_dark": speed_dark,
        "active_light": active_light,
        "active_dark": active_dark,
        "ahv_light": ahv_light,
        "ahv_dark": ahv_dark,
    }


summaries = [_session_summary(s) for s in sessions]
df = pd.DataFrame(summaries)

# ══════════════════════════════════════════════════════════════════════════
# Tabs
# ══════════════════════════════════════════════════════════════════════════
tab_traces, tab_maze, tab_general, tab_speed, tab_hd, tab_lightdark = st.tabs([
    "Behaviour Traces", "Maze Position", "General Behaviour",
    "Speed & Movement", "Head Direction", "Light/Dark Behaviour",
])

# ── Tab 1: Behaviour Traces ────────────────────────────────────────────
with tab_traces:
    st.subheader("Behaviour Variable Traces")
    st.caption("Time-series traces of speed, head direction, and angular head velocity for a selected session.")

    session_labels_tr = [f"{s['exp_id']} ({s['celltype']})" for s in sessions]
    sel_tr = st.selectbox(
        "Session", range(len(sessions)),
        format_func=lambda i: session_labels_tr[i],
        key="behav_trace_session",
    )
    sess_tr = sessions[sel_tr]
    ft_tr = sess_tr["frame_times"]
    t_tr = ft_tr - ft_tr[0]  # relative seconds
    good_tr = ~sess_tr["bad_behav"]

    # Helper: add dark epoch shading
    def _shade_dark(fig, light_on, t_rel):
        ds = np.where(np.diff(light_on.astype(int)) == -1)[0]
        de = np.where(np.diff(light_on.astype(int)) == 1)[0]
        if not light_on[0]:
            ds = np.concatenate([[0], ds])
        if not light_on[-1]:
            de = np.concatenate([de, [len(light_on) - 1]])
        for s_, e_ in zip(ds, de):
            fig.add_vrect(
                x0=t_rel[s_], x1=t_rel[min(e_, len(t_rel) - 1)],
                fillcolor="gray", opacity=0.15, line_width=0,
            )

    # Speed trace
    fig_sp = go.Figure()
    fig_sp.add_trace(go.Scatter(
        x=t_tr, y=sess_tr["speed_cm_s"],
        mode="lines", line=dict(width=0.8, color="steelblue"), name="Speed",
    ))
    _shade_dark(fig_sp, sess_tr["light_on"], t_tr)
    fig_sp.update_layout(
        height=250, template="plotly_white",
        xaxis_title="Time (s)", yaxis_title="Speed (cm/s)",
        title="Speed", margin=dict(l=50, r=20, t=35, b=30),
    )
    st.plotly_chart(fig_sp, use_container_width=True, key="behav_fig_speed_trace")

    # HD trace (wrap to [0, 360] for display)
    hd_wrapped = sess_tr["hd_deg"] % 360
    fig_hd = go.Figure()
    fig_hd.add_trace(go.Scatter(
        x=t_tr, y=hd_wrapped,
        mode="lines", line=dict(width=0.8, color="coral"), name="HD",
    ))
    _shade_dark(fig_hd, sess_tr["light_on"], t_tr)
    fig_hd.update_layout(
        height=250, template="plotly_white",
        xaxis_title="Time (s)", yaxis_title="Head Direction (deg)",
        yaxis=dict(range=[0, 360]),
        title="Head Direction", margin=dict(l=50, r=20, t=35, b=30),
    )
    st.plotly_chart(fig_hd, use_container_width=True, key="behav_fig_hd_trace")

    # AHV trace
    hd_rad_tr = np.deg2rad(sess_tr["hd_deg"])
    dhd_tr = np.diff(hd_rad_tr)
    dhd_tr = np.arctan2(np.sin(dhd_tr), np.cos(dhd_tr))
    dt_tr = np.median(np.diff(ft_tr)) if len(ft_tr) > 1 else 1.0
    ahv_tr = np.rad2deg(dhd_tr) / dt_tr
    fig_ahv = go.Figure()
    fig_ahv.add_trace(go.Scatter(
        x=t_tr[:-1], y=ahv_tr,
        mode="lines", line=dict(width=0.5, color="green"), name="AHV",
    ))
    _shade_dark(fig_ahv, sess_tr["light_on"], t_tr)
    fig_ahv.update_layout(
        height=250, template="plotly_white",
        xaxis_title="Time (s)", yaxis_title="AHV (deg/s)",
        title="Angular Head Velocity", margin=dict(l=50, r=20, t=35, b=30),
    )
    st.plotly_chart(fig_ahv, use_container_width=True, key="behav_fig_ahv_trace")

    # Active/inactive state
    fig_act = go.Figure()
    fig_act.add_trace(go.Scatter(
        x=t_tr, y=sess_tr["active"].astype(int),
        mode="lines", line=dict(width=1, color="purple"), name="Active",
        fill="tozeroy", fillcolor="rgba(128,0,128,0.15)",
    ))
    _shade_dark(fig_act, sess_tr["light_on"], t_tr)
    fig_act.update_layout(
        height=150, template="plotly_white",
        xaxis_title="Time (s)", yaxis_title="Active",
        yaxis=dict(tickvals=[0, 1], ticktext=["Inactive", "Active"]),
        title="Movement State", margin=dict(l=50, r=20, t=35, b=30),
    )
    st.plotly_chart(fig_act, use_container_width=True, key="behav_fig_active_trace")


# ── Tab 2: Maze Position Map ─────────────────────────────────────────
with tab_maze:
    st.subheader("2D Position & Maze Map")
    st.caption("Trajectory and behavioural variable maps in maze coordinates.")

    session_labels_mz = [f"{s['exp_id']} ({s['celltype']})" for s in sessions]
    sel_mz = st.selectbox(
        "Session", range(len(sessions)),
        format_func=lambda i: session_labels_mz[i],
        key="behav_maze_session",
    )
    sess_mz = sessions[sel_mz]
    good_mz = ~sess_mz["bad_behav"]

    has_position = sess_mz.get("x_mm") is not None and sess_mz.get("y_mm") is not None
    has_maze = sess_mz.get("x_maze") is not None and sess_mz.get("y_maze") is not None

    if not has_position:
        st.info(
            "Position data not available in sync.h5. Re-run Stage 5 to include "
            "x_mm, y_mm, x_maze, y_maze from kinematics.h5."
        )
    else:
        # Use maze coordinates if available, otherwise mm
        if has_maze:
            x_pos = sess_mz["x_maze"][good_mz]
            y_pos = sess_mz["y_maze"][good_mz]
            x_label, y_label = "X (maze units)", "Y (maze units)"
        else:
            x_pos = sess_mz["x_mm"][good_mz]
            y_pos = sess_mz["y_mm"][good_mz]
            x_label, y_label = "X (mm)", "Y (mm)"

        speed_mz = sess_mz["speed_cm_s"][good_mz]
        hd_mz = sess_mz["hd_deg"][good_mz] % 360
        light_mz = sess_mz["light_on"][good_mz]
        ft_mz = sess_mz["frame_times"][good_mz]
        t_mz = ft_mz - ft_mz[0]

        col1, col2 = st.columns(2)

        # Trajectory colored by time
        with col1:
            st.markdown("#### Trajectory (colored by time)")
            fig_traj = go.Figure()
            fig_traj.add_trace(go.Scatter(
                x=x_pos, y=y_pos,
                mode="lines", line=dict(width=0.5, color="gray"),
                showlegend=False, opacity=0.3,
            ))
            fig_traj.add_trace(go.Scatter(
                x=x_pos, y=y_pos,
                mode="markers",
                marker=dict(
                    size=2, color=t_mz, colorscale="Viridis",
                    colorbar=dict(title="Time (s)", len=0.5),
                ),
                showlegend=False,
            ))
            fig_traj.update_layout(
                height=450, template="plotly_white",
                xaxis_title=x_label, yaxis_title=y_label,
                yaxis=dict(scaleanchor="x"),
            )
            st.plotly_chart(fig_traj, use_container_width=True, key="behav_fig_traj")

        # Trajectory colored by speed
        with col2:
            st.markdown("#### Trajectory (colored by speed)")
            fig_speed_map = go.Figure()
            fig_speed_map.add_trace(go.Scatter(
                x=x_pos, y=y_pos,
                mode="markers",
                marker=dict(
                    size=2, color=speed_mz, colorscale="Hot",
                    cmin=0, cmax=float(np.percentile(speed_mz, 95)),
                    colorbar=dict(title="Speed (cm/s)", len=0.5),
                ),
                showlegend=False,
            ))
            fig_speed_map.update_layout(
                height=450, template="plotly_white",
                xaxis_title=x_label, yaxis_title=y_label,
                yaxis=dict(scaleanchor="x"),
            )
            st.plotly_chart(fig_speed_map, use_container_width=True, key="behav_fig_speed_map")

        col3, col4 = st.columns(2)

        # Trajectory colored by HD
        with col3:
            st.markdown("#### Trajectory (colored by head direction)")
            fig_hd_map = go.Figure()
            fig_hd_map.add_trace(go.Scatter(
                x=x_pos, y=y_pos,
                mode="markers",
                marker=dict(
                    size=2, color=hd_mz, colorscale="HSV",
                    cmin=0, cmax=360,
                    colorbar=dict(title="HD (deg)", len=0.5),
                ),
                showlegend=False,
            ))
            fig_hd_map.update_layout(
                height=450, template="plotly_white",
                xaxis_title=x_label, yaxis_title=y_label,
                yaxis=dict(scaleanchor="x"),
            )
            st.plotly_chart(fig_hd_map, use_container_width=True, key="behav_fig_hd_map")

        # Trajectory colored by light/dark
        with col4:
            st.markdown("#### Trajectory (light vs dark)")
            fig_ld_map = go.Figure()
            fig_ld_map.add_trace(go.Scatter(
                x=x_pos[light_mz], y=y_pos[light_mz],
                mode="markers", marker=dict(size=2, color="#f0c929", opacity=0.4),
                name="Light",
            ))
            fig_ld_map.add_trace(go.Scatter(
                x=x_pos[~light_mz], y=y_pos[~light_mz],
                mode="markers", marker=dict(size=2, color="#4a4a4a", opacity=0.4),
                name="Dark",
            ))
            fig_ld_map.update_layout(
                height=450, template="plotly_white",
                xaxis_title=x_label, yaxis_title=y_label,
                yaxis=dict(scaleanchor="x"),
            )
            st.plotly_chart(fig_ld_map, use_container_width=True, key="behav_fig_ld_map")

        # Occupancy heatmap
        st.markdown("#### Occupancy Heatmap")
        n_bins_occ = st.slider("Bins", 10, 60, 30, key="behav_occ_bins")
        x_edges = np.linspace(float(np.nanmin(x_pos)), float(np.nanmax(x_pos)), n_bins_occ + 1)
        y_edges = np.linspace(float(np.nanmin(y_pos)), float(np.nanmax(y_pos)), n_bins_occ + 1)
        valid_pos = np.isfinite(x_pos) & np.isfinite(y_pos)
        occ, _, _ = np.histogram2d(x_pos[valid_pos], y_pos[valid_pos], bins=[x_edges, y_edges])
        dt_occ = np.median(np.diff(sess_mz["frame_times"])) if len(sess_mz["frame_times"]) > 1 else 1.0
        occ_s = occ * dt_occ  # convert to seconds

        fig_occ = go.Figure(data=go.Heatmap(
            z=occ_s.T, colorscale="Blues",
            colorbar=dict(title="Time (s)"),
        ))
        fig_occ.update_layout(
            height=450, template="plotly_white",
            xaxis_title=x_label, yaxis_title=y_label,
            yaxis=dict(scaleanchor="x"),
        )
        st.plotly_chart(fig_occ, use_container_width=True, key="behav_fig_occ")


# ── Tab 3: General Behaviour ────────────────────────────────────────────
with tab_general:
    st.subheader("Per-Session Summary")

    # Summary table
    display_df = df[[
        "exp_id", "celltype", "total_dur_s", "active_frac", "mean_speed",
        "median_speed", "distance_cm", "light_time_s", "dark_time_s", "mean_ahv_deg_s",
    ]].copy()
    display_df.columns = [
        "Session", "Cell Type", "Duration (s)", "Active Fraction",
        "Mean Speed (cm/s)", "Median Speed (cm/s)", "Distance (cm)",
        "Light Time (s)", "Dark Time (s)", "Mean AHV (deg/s)",
    ]
    st.dataframe(
        display_df.style.format({
            "Duration (s)": "{:.1f}",
            "Active Fraction": "{:.3f}",
            "Mean Speed (cm/s)": "{:.2f}",
            "Median Speed (cm/s)": "{:.2f}",
            "Distance (cm)": "{:.1f}",
            "Light Time (s)": "{:.1f}",
            "Dark Time (s)": "{:.1f}",
            "Mean AHV (deg/s)": "{:.1f}",
        }),
        use_container_width=True,
        hide_index=True,
    )

    col1, col2 = st.columns(2)

    # Bar chart: session durations colored by celltype
    with col1:
        st.markdown("#### Session Durations by Cell Type")
        fig_dur = px.bar(
            df, x="exp_id", y="total_dur_s", color="celltype",
            color_discrete_map=CELLTYPE_COLORS,
            labels={"exp_id": "Session", "total_dur_s": "Duration (s)", "celltype": "Cell Type"},
        )
        fig_dur.update_layout(
            xaxis_tickangle=-45, template="plotly_white", height=400,
            showlegend=True,
        )
        st.plotly_chart(fig_dur, use_container_width=True, key="behav_fig_dur")

    # Box plots: speed distribution by celltype
    with col2:
        st.markdown("#### Speed Distribution by Cell Type")
        fig_speed_box = px.box(
            df, x="celltype", y="mean_speed", color="celltype",
            color_discrete_map=CELLTYPE_COLORS,
            points="all",
            labels={"celltype": "Cell Type", "mean_speed": "Mean Speed (cm/s)"},
        )
        fig_speed_box.update_layout(template="plotly_white", height=400, showlegend=False)
        st.plotly_chart(fig_speed_box, use_container_width=True, key="behav_fig_speed_box")

    col3, col4 = st.columns(2)

    # Box plots: active fraction by celltype
    with col3:
        st.markdown("#### Active Fraction by Cell Type")
        fig_active_box = px.box(
            df, x="celltype", y="active_frac", color="celltype",
            color_discrete_map=CELLTYPE_COLORS,
            points="all",
            labels={"celltype": "Cell Type", "active_frac": "Active Fraction"},
        )
        fig_active_box.update_layout(template="plotly_white", height=400, showlegend=False)
        st.plotly_chart(fig_active_box, use_container_width=True, key="behav_fig_active_box")

    # Scatter: speed vs AHV
    with col4:
        st.markdown("#### Speed vs Angular Head Velocity")
        fig_scatter = px.scatter(
            df, x="mean_speed", y="mean_ahv_deg_s", color="celltype",
            color_discrete_map=CELLTYPE_COLORS,
            hover_data=["exp_id"],
            labels={
                "mean_speed": "Mean Speed (cm/s)",
                "mean_ahv_deg_s": "Mean AHV (deg/s)",
                "celltype": "Cell Type",
            },
        )
        fig_scatter.update_layout(template="plotly_white", height=400)
        st.plotly_chart(fig_scatter, use_container_width=True, key="behav_fig_scatter")


# ── Tab 2: Speed & Movement ─────────────────────────────────────────────
with tab_speed:
    st.subheader("Speed & Movement Analysis")

    col1, col2 = st.columns(2)

    # Speed histogram: all frames pooled, split by light/dark
    with col1:
        st.markdown("#### Speed Distribution: Light vs Dark")
        all_speed_light = []
        all_speed_dark = []
        for s in sessions:
            good = ~s["bad_behav"]
            light_mask = s["light_on"] & good
            dark_mask = ~s["light_on"] & good
            if light_mask.any():
                all_speed_light.append(s["speed_cm_s"][light_mask])
            if dark_mask.any():
                all_speed_dark.append(s["speed_cm_s"][dark_mask])

        fig_speed_hist = go.Figure()
        if all_speed_light:
            pooled_light = np.concatenate(all_speed_light)
            # Clip extreme values for visualization
            pooled_light = pooled_light[pooled_light < np.percentile(pooled_light, 99)]
            fig_speed_hist.add_trace(go.Histogram(
                x=pooled_light, name="Light", opacity=0.6,
                marker_color="#f0c929", nbinsx=80,
            ))
        if all_speed_dark:
            pooled_dark = np.concatenate(all_speed_dark)
            pooled_dark = pooled_dark[pooled_dark < np.percentile(pooled_dark, 99)]
            fig_speed_hist.add_trace(go.Histogram(
                x=pooled_dark, name="Dark", opacity=0.6,
                marker_color="#4a4a4a", nbinsx=80,
            ))
        fig_speed_hist.update_layout(
            barmode="overlay", template="plotly_white", height=400,
            xaxis_title="Speed (cm/s)", yaxis_title="Frame count",
        )
        st.plotly_chart(fig_speed_hist, use_container_width=True, key="behav_fig_speed_hist")

    # Speed by celltype comparison
    with col2:
        st.markdown("#### Speed by Cell Type")
        speed_data = []
        for s in sessions:
            good = ~s["bad_behav"]
            if good.any():
                speed_data.append({
                    "celltype": s["celltype"],
                    "mean_speed": float(np.nanmean(s["speed_cm_s"][good])),
                    "median_speed": float(np.nanmedian(s["speed_cm_s"][good])),
                    "exp_id": s["exp_id"],
                })
        if speed_data:
            speed_df = pd.DataFrame(speed_data)
            fig_speed_ct = px.box(
                speed_df, x="celltype", y="mean_speed", color="celltype",
                color_discrete_map=CELLTYPE_COLORS,
                points="all",
                labels={"celltype": "Cell Type", "mean_speed": "Mean Speed (cm/s)"},
            )
            fig_speed_ct.update_layout(template="plotly_white", height=400, showlegend=False)
            st.plotly_chart(fig_speed_ct, use_container_width=True, key="behav_fig_speed_ct")

    # Speed over time for selected session
    st.markdown("#### Speed Over Time (Single Session)")
    session_labels = [f"{s['exp_id']} ({s['celltype']})" for s in sessions]
    sel_idx = st.selectbox(
        "Select session", range(len(sessions)),
        format_func=lambda i: session_labels[i],
        key="behav_speed_session",
    )
    sess = sessions[sel_idx]
    ft = sess["frame_times"]
    t_rel = ft - ft[0]  # relative time in seconds
    fig_speed_time = go.Figure()
    fig_speed_time.add_trace(go.Scatter(
        x=t_rel, y=sess["speed_cm_s"],
        mode="lines", line=dict(width=0.5, color="steelblue"),
        name="Speed",
    ))
    # Shade dark epochs
    light_on = sess["light_on"]
    dark_starts = np.where(np.diff(light_on.astype(int)) == -1)[0]
    dark_ends = np.where(np.diff(light_on.astype(int)) == 1)[0]
    if not light_on[0]:
        dark_starts = np.concatenate([[0], dark_starts])
    if not light_on[-1]:
        dark_ends = np.concatenate([dark_ends, [len(light_on) - 1]])
    for ds, de in zip(dark_starts, dark_ends):
        fig_speed_time.add_vrect(
            x0=t_rel[ds], x1=t_rel[min(de, len(t_rel) - 1)],
            fillcolor="gray", opacity=0.15, line_width=0,
        )
    fig_speed_time.update_layout(
        template="plotly_white", height=350,
        xaxis_title="Time (s)", yaxis_title="Speed (cm/s)",
        title=f"Speed trace: {sess['exp_id']}",
    )
    st.plotly_chart(fig_speed_time, use_container_width=True, key="behav_fig_speed_time")

    # Active/inactive bout duration distributions
    st.markdown("#### Active/Inactive Bout Durations")
    all_active_bouts = []
    all_inactive_bouts = []
    for s in sessions:
        good = ~s["bad_behav"]
        active = s["active"] & good
        dt = np.median(np.diff(s["frame_times"])) if len(s["frame_times"]) > 1 else 1.0
        # Find bouts via run-length encoding
        changes = np.diff(active.astype(int))
        starts = np.where(changes == 1)[0] + 1
        ends = np.where(changes == -1)[0] + 1
        if active[0]:
            starts = np.concatenate([[0], starts])
        if active[-1]:
            ends = np.concatenate([ends, [len(active)]])
        for bs, be in zip(starts, ends):
            all_active_bouts.append((be - bs) * dt)

        # Inactive bouts
        inactive = ~s["active"] & good
        changes_i = np.diff(inactive.astype(int))
        starts_i = np.where(changes_i == 1)[0] + 1
        ends_i = np.where(changes_i == -1)[0] + 1
        if inactive[0]:
            starts_i = np.concatenate([[0], starts_i])
        if inactive[-1]:
            ends_i = np.concatenate([ends_i, [len(inactive)]])
        for bs, be in zip(starts_i, ends_i):
            all_inactive_bouts.append((be - bs) * dt)

    col_b1, col_b2 = st.columns(2)
    with col_b1:
        if all_active_bouts:
            fig_ab = px.histogram(
                x=all_active_bouts, nbins=60,
                labels={"x": "Bout Duration (s)", "y": "Count"},
                title="Active Bout Durations",
            )
            fig_ab.update_layout(template="plotly_white", height=350)
            st.plotly_chart(fig_ab, use_container_width=True, key="behav_fig_active_bouts")
            st.caption(
                f"N = {len(all_active_bouts)} bouts, "
                f"median = {np.median(all_active_bouts):.2f} s"
            )
    with col_b2:
        if all_inactive_bouts:
            fig_ib = px.histogram(
                x=all_inactive_bouts, nbins=60,
                labels={"x": "Bout Duration (s)", "y": "Count"},
                title="Inactive Bout Durations",
            )
            fig_ib.update_layout(template="plotly_white", height=350)
            st.plotly_chart(fig_ib, use_container_width=True, key="behav_fig_inactive_bouts")
            st.caption(
                f"N = {len(all_inactive_bouts)} bouts, "
                f"median = {np.median(all_inactive_bouts):.2f} s"
            )


# ── Tab 3: Head Direction ───────────────────────────────────────────────
with tab_hd:
    st.subheader("Head Direction Occupancy")

    col1, col2 = st.columns(2)

    # HD occupancy histogram — all frames, all sessions pooled
    with col1:
        st.markdown("#### HD Occupancy (All Sessions Pooled)")
        all_hd = []
        for s in sessions:
            good = ~s["bad_behav"]
            if good.any():
                all_hd.append(s["hd_deg"][good])
        if all_hd:
            pooled_hd = np.concatenate(all_hd)
            fig_hd_occ = go.Figure()
            fig_hd_occ.add_trace(go.Histogram(
                x=pooled_hd, nbinsx=72,  # 5-degree bins
                marker_color="steelblue", opacity=0.8,
            ))
            fig_hd_occ.update_layout(
                template="plotly_white", height=400,
                xaxis_title="Head Direction (deg)", yaxis_title="Frame count",
                xaxis=dict(range=[0, 360]),
            )
            st.plotly_chart(fig_hd_occ, use_container_width=True, key="behav_fig_hd_occ")
            st.caption(
                "If the distribution is non-uniform, animals may preferentially "
                "face certain directions in the maze."
            )

    # HD occupancy: light vs dark overlay
    with col2:
        st.markdown("#### HD Occupancy: Light vs Dark")
        all_hd_light = []
        all_hd_dark = []
        for s in sessions:
            good = ~s["bad_behav"]
            light_mask = s["light_on"] & good
            dark_mask = ~s["light_on"] & good
            if light_mask.any():
                all_hd_light.append(s["hd_deg"][light_mask])
            if dark_mask.any():
                all_hd_dark.append(s["hd_deg"][dark_mask])

        fig_hd_ld = go.Figure()
        if all_hd_light:
            fig_hd_ld.add_trace(go.Histogram(
                x=np.concatenate(all_hd_light), nbinsx=72,
                name="Light", marker_color="#f0c929", opacity=0.6,
            ))
        if all_hd_dark:
            fig_hd_ld.add_trace(go.Histogram(
                x=np.concatenate(all_hd_dark), nbinsx=72,
                name="Dark", marker_color="#4a4a4a", opacity=0.6,
            ))
        fig_hd_ld.update_layout(
            barmode="overlay", template="plotly_white", height=400,
            xaxis_title="Head Direction (deg)", yaxis_title="Frame count",
            xaxis=dict(range=[0, 360]),
        )
        st.plotly_chart(fig_hd_ld, use_container_width=True, key="behav_fig_hd_ld")

    col3, col4 = st.columns(2)

    # AHV distribution — all sessions pooled
    with col3:
        st.markdown("#### Angular Head Velocity Distribution")
        all_ahv = []
        for s in sessions:
            good = ~s["bad_behav"]
            hd = s["hd_deg"]
            dt = np.median(np.diff(s["frame_times"])) if len(s["frame_times"]) > 1 else 1.0
            hd_rad = np.deg2rad(hd)
            dhd = np.diff(hd_rad)
            dhd = np.arctan2(np.sin(dhd), np.cos(dhd))
            ahv_deg = np.rad2deg(np.abs(dhd)) / dt
            good_mask = good[1:] & good[:-1]
            if good_mask.any():
                all_ahv.append(ahv_deg[good_mask])
        if all_ahv:
            pooled_ahv = np.concatenate(all_ahv)
            # Clip to 99th percentile for visualization
            clip_val = np.percentile(pooled_ahv, 99)
            pooled_ahv = pooled_ahv[pooled_ahv < clip_val]
            fig_ahv = go.Figure()
            fig_ahv.add_trace(go.Histogram(
                x=pooled_ahv, nbinsx=80,
                marker_color="coral", opacity=0.8,
            ))
            fig_ahv.update_layout(
                template="plotly_white", height=400,
                xaxis_title="AHV (deg/s)", yaxis_title="Frame count",
            )
            st.plotly_chart(fig_ahv, use_container_width=True, key="behav_fig_ahv_dist")

    # AHV: light vs dark
    with col4:
        st.markdown("#### AHV: Light vs Dark")
        all_ahv_light = []
        all_ahv_dark = []
        for s in sessions:
            good = ~s["bad_behav"]
            hd = s["hd_deg"]
            dt = np.median(np.diff(s["frame_times"])) if len(s["frame_times"]) > 1 else 1.0
            hd_rad = np.deg2rad(hd)
            dhd = np.diff(hd_rad)
            dhd = np.arctan2(np.sin(dhd), np.cos(dhd))
            ahv_deg = np.rad2deg(np.abs(dhd)) / dt
            good_mask = good[1:] & good[:-1]
            light_ahv_mask = s["light_on"][1:] & s["light_on"][:-1] & good_mask
            dark_ahv_mask = ~s["light_on"][1:] & ~s["light_on"][:-1] & good_mask
            if light_ahv_mask.any():
                all_ahv_light.append(ahv_deg[light_ahv_mask])
            if dark_ahv_mask.any():
                all_ahv_dark.append(ahv_deg[dark_ahv_mask])

        fig_ahv_ld = go.Figure()
        if all_ahv_light:
            pooled_al = np.concatenate(all_ahv_light)
            clip_val = np.percentile(pooled_al, 99)
            fig_ahv_ld.add_trace(go.Histogram(
                x=pooled_al[pooled_al < clip_val], nbinsx=80,
                name="Light", marker_color="#f0c929", opacity=0.6,
            ))
        if all_ahv_dark:
            pooled_ad = np.concatenate(all_ahv_dark)
            clip_val = np.percentile(pooled_ad, 99)
            fig_ahv_ld.add_trace(go.Histogram(
                x=pooled_ad[pooled_ad < clip_val], nbinsx=80,
                name="Dark", marker_color="#4a4a4a", opacity=0.6,
            ))
        fig_ahv_ld.update_layout(
            barmode="overlay", template="plotly_white", height=400,
            xaxis_title="AHV (deg/s)", yaxis_title="Frame count",
        )
        st.plotly_chart(fig_ahv_ld, use_container_width=True, key="behav_fig_ahv_ld")


# ── Tab 4: Light/Dark Behaviour ─────────────────────────────────────────
with tab_lightdark:
    st.subheader("Light vs Dark Behavioural Comparisons")
    st.caption(
        "Each dot represents one session. Paired comparisons using Wilcoxon "
        "signed-rank test."
    )

    # Filter sessions with valid light/dark data
    valid_ld = df.dropna(subset=["speed_light", "speed_dark"])

    if len(valid_ld) < 3:
        st.warning("Not enough sessions with both light and dark epochs for comparison.")
        st.stop()

    col1, col2 = st.columns(2)

    # Per-session: speed in light vs dark
    with col1:
        st.markdown("#### Speed: Light vs Dark")
        fig_speed_ld, stat_speed = paired_condition_scatter(
            valid_ld["speed_light"].values,
            valid_ld["speed_dark"].values,
            label1="Light",
            label2="Dark",
            measure_name="Mean Speed (cm/s)",
            title="Speed: Light vs Dark",
        )
        st.plotly_chart(fig_speed_ld, use_container_width=True, key="behav_fig_speed_ld")
        st.caption(
            f"Wilcoxon W = {stat_speed['W']:.1f}, "
            f"p = {format_pvalue(stat_speed['p'])}, "
            f"n = {stat_speed['n']} sessions"
        )

    # Per-session: active fraction in light vs dark
    with col2:
        st.markdown("#### Active Fraction: Light vs Dark")
        valid_af = df.dropna(subset=["active_light", "active_dark"])
        if len(valid_af) >= 3:
            fig_af_ld, stat_af = paired_condition_scatter(
                valid_af["active_light"].values,
                valid_af["active_dark"].values,
                label1="Light",
                label2="Dark",
                measure_name="Active Fraction",
                title="Active Fraction: Light vs Dark",
            )
            st.plotly_chart(fig_af_ld, use_container_width=True, key="behav_fig_af_ld")
            st.caption(
                f"Wilcoxon W = {stat_af['W']:.1f}, "
                f"p = {format_pvalue(stat_af['p'])}, "
                f"n = {stat_af['n']} sessions"
            )
        else:
            st.info("Not enough sessions for active fraction comparison.")

    col3, col4 = st.columns(2)

    # Per-session: AHV in light vs dark
    with col3:
        st.markdown("#### AHV: Light vs Dark")
        valid_ahv = df.dropna(subset=["ahv_light", "ahv_dark"])
        if len(valid_ahv) >= 3:
            fig_ahv_ld_paired, stat_ahv = paired_condition_scatter(
                valid_ahv["ahv_light"].values,
                valid_ahv["ahv_dark"].values,
                label1="Light",
                label2="Dark",
                measure_name="Mean AHV (deg/s)",
                title="AHV: Light vs Dark",
            )
            st.plotly_chart(fig_ahv_ld_paired, use_container_width=True, key="behav_fig_ahv_ld_paired")
            st.caption(
                f"Wilcoxon W = {stat_ahv['W']:.1f}, "
                f"p = {format_pvalue(stat_ahv['p'])}, "
                f"n = {stat_ahv['n']} sessions"
            )
        else:
            st.info("Not enough sessions for AHV comparison.")

    # Summary statistics table
    with col4:
        st.markdown("#### Summary Statistics")
        summary_rows = []
        for measure, light_col, dark_col in [
            ("Speed (cm/s)", "speed_light", "speed_dark"),
            ("Active Fraction", "active_light", "active_dark"),
            ("AHV (deg/s)", "ahv_light", "ahv_dark"),
        ]:
            valid = df.dropna(subset=[light_col, dark_col])
            if len(valid) >= 3:
                from scipy.stats import wilcoxon
                light_vals = valid[light_col].values
                dark_vals = valid[dark_col].values
                try:
                    w_stat, p_val = wilcoxon(light_vals, dark_vals)
                except Exception:
                    w_stat, p_val = np.nan, np.nan
                summary_rows.append({
                    "Measure": measure,
                    "Light (mean)": f"{np.mean(light_vals):.3f}",
                    "Dark (mean)": f"{np.mean(dark_vals):.3f}",
                    "Diff": f"{np.mean(light_vals) - np.mean(dark_vals):.3f}",
                    "p-value": format_pvalue(p_val),
                    "N": len(valid),
                })
        if summary_rows:
            st.dataframe(
                pd.DataFrame(summary_rows),
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("Not enough data for summary statistics.")
