"""Label Review — browse annotated training frames.

Shows every labeled training frame with body part annotations overlaid.
Generated by: uv run python scripts/render_labeled_frames.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

REVIEW_DIR = Path("review_frames")

st.title("Label Review")
st.caption(
    "Annotated training frames with labeled body parts drawn on. "
    "Regenerate with: `uv run python scripts/render_labeled_frames.py`"
)

if not REVIEW_DIR.exists() or not list(REVIEW_DIR.glob("*.png")):
    st.warning(
        "No review frames found. Generate them with:\n\n"
        "```\nuv run python scripts/render_labeled_frames.py\n```"
    )
    st.stop()

pngs = sorted(REVIEW_DIR.glob("*.png"))

# Parse filenames to extract session and frame info
frames = []
for p in pngs:
    # Format: shortid_NN_fullid_movieframe.png
    name = p.stem
    parts = name.split("_", 3)
    if len(parts) >= 3:
        short = f"{parts[0]}_{parts[1]}"
        frame_num = parts[2] if len(parts) > 2 else "?"
    else:
        short = name[:20]
        frame_num = "?"
    frames.append({"path": p, "name": name, "short": short, "frame_num": frame_num})

# Session filter
sessions = sorted(set(f["short"] for f in frames))
all_label = "All sessions"

col1, col2 = st.columns([2, 3])
with col1:
    selected_session = st.selectbox("Session", [all_label] + sessions, key="lr_session")
with col2:
    cols_per_row = st.slider("Columns", 2, 6, 4, key="lr_cols")

if selected_session != all_label:
    frames = [f for f in frames if f["short"] == selected_session]

st.markdown(f"**{len(frames)} frames**")

# Display in grid
for i in range(0, len(frames), cols_per_row):
    cols = st.columns(cols_per_row)
    for j, col in enumerate(cols):
        idx = i + j
        if idx >= len(frames):
            break
        f = frames[idx]
        with col:
            st.image(str(f["path"]), caption=f["name"], use_container_width=True)
