function plotPCACellType(dirs, metricsTable, plotIndexStart, cellTypeLabel, cellTypePrefixes, excludeCols)

    idxEphysAll = find(metricsTable.has_ephys_complete);
    idxMorphAll = find(metricsTable.has_morph_good);
    idxEphysMorph = find(metricsTable.has_ephys_complete & metricsTable.has_morph_good);
    
    ephysPrefix = 'ephys_';
    ephysPassivePrefix = 'ephys_passive_';
    ephysActivePrefix = 'ephys_active_';
    morphPrefix = 'morph_';
    morphApiPrefix = 'morph_api_';
    morphBasPrefix = 'morph_bas_';    
    
    plotIndex = plotIndexStart;
    
    % All Ephys
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxEphysAll, ...
              {ephysPrefix}, ...
              'Ephys', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-Ephys', ...
              cellTypePrefixes, ...
              excludeCols);
    
    % All Ephys passive
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxEphysAll, ...
              {ephysPassivePrefix}, ...
              'Ephys passive', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-EphysPassive', ...
              cellTypePrefixes, ...
              excludeCols);
    
    % All Ephys Active
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxEphysAll, ...
              {ephysActivePrefix}, ...
              'Ephys active', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-EphysActive', ...
              cellTypePrefixes, ...
              excludeCols);
    
    % All Morph
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxMorphAll, ...
              {morphPrefix}, ...
              'Morphology', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-Morph', ...
              cellTypePrefixes, ...
              excludeCols);
    
    % All Morph apical
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxMorphAll, ...
              {morphApiPrefix}, ...
              'Apical morphology', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-MorphApical', ...
              cellTypePrefixes, ...
              excludeCols);
    
    % All Morph basal
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxMorphAll, ...
              {morphBasPrefix}, ...
              'Basal Morphology', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-MorphBasal', ...
              cellTypePrefixes, ...
              excludeCols);
    
    
    % Ephys and morph
    plotIndex = plotIndex + 1;
    plotPCPCA(metricsTable, ...
              idxEphysMorph, ...
              {ephysPrefix, morphPrefix}, ...
              'Ephys and morphology', ...
              dirs.pcaPlotDir, ...
              cellTypeLabel, ...
              plotIndex, ...
              'PCA-EphysMorph', ...
              cellTypePrefixes, ...
              excludeCols);
    
%     % Ephys with morph
%     plotIndex = plotIndex + 1;
%     plotPCPCA(metricsTable, ...
%               idxEphysMorph, ...
%               {ephysPrefix}, ...
%               'Ephys with morphology', ...
%               dirs.pcaPlotDir, ...
%               cellTypeLabel, ...
%               plotIndex, ...
%               'PCA-EphysWithMorph', ...
%               cellTypePrefixes, ...
%               excludeCols);
%     
%     % Morph with ephys
%     plotIndex = plotIndex + 1;
%     plotPCPCA(metricsTable, ...
%               idxEphysMorph, ...
%               {morphPrefix}, ...
%               'Morphology with ephys', ...
%               dirs.pcaPlotDir, ...
%               cellTypeLabel, ...
%               plotIndex, ...
%               'PCA-MorphWithEphys', ...
%               cellTypePrefixes, ...
%               excludeCols);

end