SuperAnimalConversionTables:
  superanimal_topviewmouse:
    nose_tip: nose
    left_ear: left_ear
    right_ear: right_ear
    neck: neck
    mid_back: mid_back
    mouse_center: mouse_center
    tail_base: tail_base
Task: hm2p-retrain
TrainingFraction:
- 0.80
alphavalue: 0.7
batch_size: 8
bodyparts:
- nose_tip
- left_ear
- right_ear
- implant_base_rear
- neck
- mid_back
- mouse_center
- tail_base
colormap: rainbow
corner2move2:
- 50
- 50
cropping: false
date: Mar20
default_augmenter: default
default_net_type: resnet_50
detector_batch_size: 1
detector_snapshotindex: -1
dotsize: 12
engine: pytorch
identity: null
iteration: 0
move2corner: true
multianimalproject: false
numframes2pick: 20
pcutoff: 0.4
project_path: /Users/tristan/Neuro/hm2p-v2/sourcedata/trackers/dlc/hm2p-retrain-tristan-2026-03-20
scorer: tristan
skeleton:
- - nose_tip
  - implant_base_rear
- - nose_tip
  - left_ear
- - nose_tip
  - right_ear
- - left_ear
  - implant_base_rear
- - right_ear
  - implant_base_rear
- - left_ear
  - right_ear
- - implant_base_rear
  - neck
- - neck
  - mid_back
- - mid_back
  - mouse_center
- - mouse_center
  - tail_base
skeleton_color: black
snapshotindex: -1
start: 0
stop: 1
video_sets:
  /private/tmp/sub-1114353_ses-20210823T165950/20210823_17_00_04_1114353_maze-rose_overhead.camera-cropped.mp4:
    crop: 0, 832, 0, 608
x1: 0
x2: 640
y1: 277
y2: 624
